File content check
actris-cloudnet/cloudnet-processing pull request #45
Opened 2022-10-12 12:39 UTC by tukiains

Compare created file to (possibly) existing file. Avoid creating new version if the content has not been changed.

2022-10-13 07:43 UTC, siiptuo requested changes
Hyvää refaktointia ohessa!

2022-10-13 07:43 UTC, siiptuo commented on src/data_processing/utils.py
> +    logging.info(f"{text} differ in {var_name}: {value1} vs. {value2}")
Pitäisikö tämä olla `return` niin, että loggaus tehdään vain yhdessä paikassa?

2022-10-13 07:43 UTC, siiptuo commented on src/data_processing/utils.py
> +        )
Tämä voi heittää poikkeuksen, jos `value1` ja `value2` ovat erikokoisia.

2022-10-13 07:43 UTC, siiptuo commented on src/data_processing/utils.py
> +        assert value1 == value2, _log("variable data types", name, value1, value2)
Pitäisikö variablen dimensiot myös tarkastaa?

2022-10-13 10:43 UTC, tukiains commented on src/data_processing/utils.py
> +        )
Hyvä pointti, pitää tarkastaa koko ensin.

2022-10-13 11:07 UTC, tukiains commented on src/data_processing/utils.py
> +        assert value1 == value2, _log("variable data types", name, value1, value2)
Ei siitä haittaakaan ole..

2022-10-13 11:26 UTC, tukiains commented on src/data_processing/utils.py
> +    logging.info(f"{text} differ in {var_name}: {value1} vs. {value2}")
Joo voisi, olla, ja ehkä nuo lokitukset voisi olla debug-tasolla, kun oletus varmaankin on, että jotain on muuttunut.

2022-10-13 12:39 UTC, siiptuo commented on src/data_processing/utils.py
> +        assert value1.shape == value2.shape
Viesti olisi hyvä tännekin.

2022-10-13 12:39 UTC, siiptuo commented on src/data_processing/utils.py
> +        )
Tämän pitäisi tehdä sama:
```suggestion
        assert ma.allclose(value1, value2, rtol=1e-4), _log(
            "variable values", name, value1, value2
        )
```

2022-10-13 16:27 UTC, tukiains commented on src/data_processing/utils.py
> +        )
Aah, hyvä löytö! :+1:

2022-10-13 16:29 UTC, tukiains commented on src/data_processing/utils.py
> +        assert value1.shape == value2.shape
Joo, unohtunut. Lisätään..

2022-10-14 07:55 UTC, siiptuo approved these changes

2022-10-14 07:56 UTC, merged