Housekeeping
actris-cloudnet/cloudnet-processing pull request #48
Opened 2022-11-09 13:02 UTC by nikoleskinen

2022-11-10 06:55 UTC, tukiains requested changes
Nopeasti saatu aikaan hyödyllistä toiminnallisuutta projektiin, hyvää työtä! Koodin laatu on pääasiassa hyvää, mutta toteutusta voisi vielä siistiä:
- Vältä Pythonin sisäänrakennettuja funktioita muuttujaniminä (`id`, `type`, `min`, ym.).
- Vältä liian lyhyitä / kryptisiä muuttujanimiä ja funktioiden nimiä (`m`, `cfgs`, `df`). Ne voivat olla paikallaan, jos scope on lyhyt, mutta pitkässä funktiossa ne tekevät koodin lukemisesta raskasta.

Muita pieniä kommentteja ja ehdotuksia koodin seassa.

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +            measurements[var] = hkd.data[var]
```suggestion
    measurements  = {var: hkd.data[var] for var in cfg["vars"] if var in hkd.data}
```

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +            measurements[var] = data[var]
Tämänkin voi kirjoittaa samalla tavalla kuin yllä. Harkitse funktiota, koska teet saman asian kahteen kertaan.

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +    cfgs = toml.load(src)
Mulla IDE valittaa, että `Path` ei ole sallittu tyyppi, että pitäisi olla `str(src)` tai `src.as_posix()` ?

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +    year, month, day, hour, min, sec = [int(t) for t in rpg_seconds2date(trpg)]
```suggestion
    year, month, day, hour, minute, sec = [int(t) for t in rpg_seconds2date(trpg)]
```

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +    time_ = data["Time"]
```suggestion
```

2022-11-10 06:55 UTC, tukiains commented on src/housekeeping/housekeeping.py
> +    return args
```suggestion
def get_write_arg() -> dict:
    return {key: getenv(f"INFLUXDB_{key.upper()}") for key in ["bucket", "org"]}
```

2022-11-11 09:56 UTC, siiptuo approved these changes

2022-11-11 10:03 UTC, merged