Halo housekeeping data processing
actris-cloudnet/cloudnet-processing pull request #99
Opened 2024-12-10 12:26 UTC by nikoleskinen

2024-12-10 13:01 UTC, siiptuo requested changes

2024-12-10 13:01 UTC, siiptuo commented on src/processing/instrument.py
> +    records = _get_housekeeping_records(processor, params)
Sama myös `jobs.py`:hyn

2024-12-10 15:26 UTC, swr99ejo commented on src/housekeeping/config.toml
> +vars.internal_relative_humidity = "internal_relative_humidity"
I'd prefer "internal_relative_humidity", and we should maybe update the CL61 variable name in processing

2024-12-12 09:21 UTC, siiptuo requested changes

2024-12-12 09:21 UTC, siiptuo commented on src/processing/housekeeping_utils.py
> +    ]
Kaatuu, jos `system_parameters`-tiedostoa ei ole lähetetty.

2024-12-12 11:42 UTC, siiptuo approved these changes

2024-12-12 11:43 UTC, merged